name: e2e tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
          terraform_wrapper: false

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-validate --skip-publish --skip-sign -f .goreleaser-e2e-build.yml

      - name: Run test
        run: make copyplugins && ls e2e/test_basic/terraform.d/terraform.example.com/examplecorp/graphql/2.0.0 && make test
